export const shortTicketHtml = (shortDesc, date, detailDesc, id) => {
  const wrapper = document.createElement("div");
  wrapper.classList.add("ticket");
  wrapper.dataset.id = id;
  const short = document.createElement("div");
  short.classList.add("short");
  wrapper.appendChild(short);
  const inputCheckbox = document.createElement("input");
  inputCheckbox.type = "checkbox";
  inputCheckbox.id = "ticket1";
  short.appendChild(inputCheckbox);
  const labelChecbox = document.createElement("label");
  labelChecbox.for = "ticket1";
  labelChecbox.classList.add("label");
  labelChecbox.textContent = shortDesc;
  short.appendChild(labelChecbox);
  const spanDate = document.createElement("span");
  spanDate.classList.add("date");
  spanDate.textContent = date;
  short.appendChild(spanDate);
  const editImg = document.createElement("img");
  editImg.classList.add("edit");
  editImg.src = "./assets/images/edit.png";
  editImg.alt = "редактировать";
  short.appendChild(editImg);
  const deleteImg = document.createElement("img");
  deleteImg.classList.add("delete");
  deleteImg.src = "./assets/images/delete.png";
  deleteImg.alt = "удалить";
  short.appendChild(deleteImg);
  const description = document.createElement("div");
  description.classList.add("detailDescription");
  description.textContent = detailDesc;
  wrapper.appendChild(description);
  return wrapper;
};